-- ===========================================================================
-- 001 — esquema inicial do sistema de gestão (/restrito) no PostgreSQL
--
-- Tradução fiel do que existia no SQLite (data/gestao.db), já com todas as
-- colunas que antes eram acrescentadas por ALTER TABLE no boot. Daqui em
-- diante, mudança de estrutura é um arquivo novo nesta pasta.
--
-- VOCABULÁRIO DO INSTITUTO: a tabela se chama `pacientes` por herança do
-- código, mas na tela ela é "Usuários" — quem o instituto atende. Do mesmo
-- modo, `atendimentos.especialidade` guarda os SERVIÇOS prestados (um JSON
-- com vários). Renomear as tabelas agora só criaria risco sem ganhar nada;
-- o que o beneficiário lê está na interface, não aqui.
--
-- DUAS DECISÕES DE TIPO, para NÃO mexer na aplicação:
--  · liga/desliga (ativo, vulneravel, consentimento) continuam INTEGER 0/1, e
--    não BOOLEAN — virar boolean obrigaria a rever cada `ativo=1` do SQL, cada
--    JSON da tela e cada `if (x.ativo)` do JavaScript.
--  · datas continuam TEXT no formato ISO, como o sistema já grava, compara e
--    ordena. Ordenação alfabética de ISO é ordenação cronológica.
-- ===========================================================================

-- Operadores do sistema. perfil: admin | secretaria | profissional.
-- profissional_id liga um operador ao seu registro em `profissionais` — é
-- assim que ele enxerga "a SUA agenda".
CREATE TABLE IF NOT EXISTS g_usuarios (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome            TEXT NOT NULL,
  email           TEXT UNIQUE,
  senha_hash      TEXT NOT NULL,
  perfil          TEXT NOT NULL DEFAULT 'admin',
  ativo           INTEGER DEFAULT 1,
  profissional_id INTEGER,
  criado          TEXT
);

-- Configurações internas (chave/valor): travas de seed, contadores.
CREATE TABLE IF NOT EXISTS g_config (
  key   TEXT PRIMARY KEY,
  value TEXT
);

-- USUÁRIOS do instituto (as pessoas atendidas). A tabela mantém o nome
-- `pacientes` por herança do código de origem.
CREATE TABLE IF NOT EXISTS pacientes (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                 TEXT NOT NULL,
  foto                 TEXT,
  nascimento           TEXT,
  cpf                  TEXT,
  rg                   TEXT,
  endereco             TEXT,
  telefone             TEXT,
  email                TEXT,
  nis                  TEXT,
  cartao_sus           TEXT,
  escolaridade         TEXT,
  vulneravel           INTEGER DEFAULT 0,
  vulnerabilidade      TEXT,
  primeiro_atendimento TEXT,
  consentimento        INTEGER DEFAULT 0,
  observacoes          TEXT,
  criado               TEXT,
  pai                  TEXT,
  mae                  TEXT,
  projeto_id           INTEGER,
  -- responsável legal, exibido só quando a pessoa é menor de 18
  resp_nome            TEXT,
  resp_cpf             TEXT,
  resp_rg              TEXT,
  resp_nascimento      TEXT
);

-- Associados do instituto (quem contribui). Têm portal próprio em /externo,
-- com senha própria (hash scrypt em senha_externo).
CREATE TABLE IF NOT EXISTS associados (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT NOT NULL,
  cpf           TEXT,
  contato       TEXT,
  endereco      TEXT,
  foto          TEXT,
  vinculo       TEXT,
  adesao        TEXT,
  mensalidade   TEXT,
  status        TEXT DEFAULT 'Ativo',
  criado        TEXT,
  senha_externo TEXT
);

-- Profissionais. `especialidade` guarda um JSON com os SERVIÇOS que a pessoa
-- presta — é o que recorta a lista de serviços na agenda.
CREATE TABLE IF NOT EXISTS profissionais (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome          TEXT NOT NULL,
  especialidade TEXT,
  registro      TEXT,
  contato       TEXT,
  ativo         INTEGER DEFAULT 1
);

-- Agenda de serviços. `especialidade` guarda um JSON array com os serviços
-- daquele atendimento (um atendimento pode ter vários).
-- Regras de horário no servidor: blocos de 40min, 07-12h e 14-18h.
CREATE TABLE IF NOT EXISTS atendimentos (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id     INTEGER,
  profissional_id INTEGER,
  especialidade   TEXT,
  data            TEXT,
  hora            TEXT,
  local           TEXT,
  status          TEXT DEFAULT 'Agendado',
  observacoes     TEXT,
  criado          TEXT,
  sala            TEXT,
  valor           TEXT
);

-- Prontuário: um registro por atendimento, com o conteúdo clínico em colunas.
CREATE TABLE IF NOT EXISTS prontuario (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id     INTEGER,
  atendimento_id  INTEGER,
  profissional    TEXT,
  especialidade   TEXT,
  data            TEXT,
  avaliacao       TEXT,
  evolucao        TEXT,
  plano           TEXT,
  encaminhamentos TEXT,
  anexos          TEXT,
  responsavel     TEXT,
  criado          TEXT,
  usuario_id      INTEGER
);

-- Entregas de benefício (cesta, kit, auxílio).
CREATE TABLE IF NOT EXISTS beneficios (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome        TEXT NOT NULL,
  cpf         TEXT,
  item        TEXT,
  data        TEXT,
  foto        TEXT,
  local       TEXT,
  responsavel TEXT,
  criado      TEXT
);

-- Eventos e ações do instituto. `fotos` guarda uma galeria (JSON).
CREATE TABLE IF NOT EXISTS eventos (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo          TEXT,
  titulo        TEXT NOT NULL,
  tema          TEXT,
  local         TEXT,
  data          TEXT,
  hora          TEXT,
  publico_alvo  TEXT,
  participantes INTEGER,
  responsavel   TEXT,
  avaliacao     TEXT,
  fotos         TEXT,
  criado        TEXT
);

-- Documentos por usuário atendido.
CREATE TABLE IF NOT EXISTS documentos_gestao (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paciente_id INTEGER,
  tipo        TEXT,
  titulo      TEXT,
  arquivo     TEXT,
  data        TEXT,
  criado      TEXT
);

-- PROJETOS do instituto. Vivem aqui (e não no banco do site) desde a v2.0.0:
-- o /restrito cadastra, o site publica lendo daqui, e o /admin só visualiza.
CREATE TABLE IF NOT EXISTS projetos (
  id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title   TEXT NOT NULL,
  slug    TEXT,
  sigla   TEXT,
  status  TEXT,
  resumo  TEXT,
  publico TEXT,
  content TEXT,
  sort    INTEGER DEFAULT 0,
  criado  TEXT
);

-- SERVIÇOS prestados. Mesmo caminho dos projetos: cadastrados aqui, publicados
-- pelo site, só-leitura no /admin.
CREATE TABLE IF NOT EXISTS servicos (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title     TEXT NOT NULL,
  categoria TEXT,
  sort      INTEGER DEFAULT 0,
  criado    TEXT
);

-- ------------------------------- índices ----------------------------------
CREATE INDEX IF NOT EXISTS idx_atend_data ON atendimentos(data);
CREATE INDEX IF NOT EXISTS idx_atend_pac  ON atendimentos(paciente_id);
CREATE INDEX IF NOT EXISTS idx_atend_prof ON atendimentos(profissional_id);
CREATE INDEX IF NOT EXISTS idx_pront_pac  ON prontuario(paciente_id);
CREATE INDEX IF NOT EXISTS idx_doc_pac    ON documentos_gestao(paciente_id);
CREATE INDEX IF NOT EXISTS idx_proj_sort  ON projetos(sort);
CREATE INDEX IF NOT EXISTS idx_serv_sort  ON servicos(sort);

-- O slug do projeto é o endereço da página no site: dois iguais fariam uma
-- página sobrescrever a outra na publicação.
CREATE UNIQUE INDEX IF NOT EXISTS idx_proj_slug
  ON projetos(slug) WHERE slug IS NOT NULL AND slug <> '';
