-- ===========================================================================
-- 002 — trilha de auditoria
--
-- Registra o que cada pessoa fez no sistema: entrou, saiu, abriu uma tela,
-- cadastrou, editou, excluiu. É o que responde "quem mexeu nisto, e quando" —
-- pergunta que, num sistema de prontuário, uma hora aparece.
--
-- DUAS COLUNAS SÃO CIFRADAS (`resumo` e `detalhe`), porque elas carregam o
-- conteúdo do que foi feito: o nome do paciente cadastrado, o CPF corrigido, o
-- trecho da evolução alterada. Sem isso, a auditoria viraria a porta dos fundos
-- do banco — todo o cuidado com as outras tabelas cairia por terra aqui.
--
-- O que fica LEGÍVEL é o que serve para filtrar e agrupar sem revelar paciente:
-- data, IP, quem fez, perfil, tipo de ação e módulo. É por essas colunas que a
-- tela filtra, e é por isso que elas não podem ser cifradas.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS auditoria (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  criado       TEXT NOT NULL,          -- ISO 8601, como o resto do sistema
  ip           TEXT,
  usuario_id   INTEGER,
  usuario_nome TEXT,                   -- nome de quem operou (equipe, não paciente)
  perfil       TEXT,                   -- admin | secretaria | profissional
  acao         TEXT NOT NULL,          -- login | logout | acesso | criar | editar | excluir | …
  modulo       TEXT,                   -- pacientes | prontuario | anamneses | …
  entidade_id  INTEGER,                -- id do registro afetado, quando houver
  resumo       TEXT,                   -- CIFRADO — uma linha do que aconteceu
  detalhe      TEXT,                   -- CIFRADO — JSON com o antes/depois
  rota         TEXT,
  metodo       TEXT
);

-- A tela abre sempre pelo mais recente e filtra por período: é este índice que
-- evita varrer a tabela inteira quando ela tiver centenas de milhares de linhas.
CREATE INDEX IF NOT EXISTS idx_aud_criado  ON auditoria(criado DESC);
CREATE INDEX IF NOT EXISTS idx_aud_usuario ON auditoria(usuario_id);
CREATE INDEX IF NOT EXISTS idx_aud_acao    ON auditoria(acao);
CREATE INDEX IF NOT EXISTS idx_aud_modulo  ON auditoria(modulo);
