-- ===========================================================================
-- 006 — o prontuário vira PASTA
--
-- COMO ERA: cada linha de `prontuario` era um atendimento isolado, com quatro
-- caixas de texto (avaliação, evolução, plano, encaminhamentos) preenchidas
-- de uma vez. Acompanhar alguém por um ano significava abrir dezenas de linhas
-- soltas, uma a uma, sem ordem nem continuidade — e não havia como dizer "esta
-- pessoa concluiu o acompanhamento no Serviço Social, mas segue na Psicologia".
--
-- COMO FICA: uma PASTA por pessoa + serviço, e dentro dela LANÇAMENTOS datados.
-- Cada avaliação, evolução, plano ou encaminhamento é uma linha própria, com
-- data e autor. A pasta tem número (PR-AAAA-00000), situação (Ativo/Alta) e
-- reúne os agendamentos daquele acompanhamento.
--
-- POR QUE UM SERVIÇO POR PASTA: a alta é DA PASTA. Se uma pasta cobrisse vários
-- serviços ao mesmo tempo, encerrar um obrigaria a encerrar todos — que é
-- exatamente o que a equipe não pode fazer. Por isso `especialidade` deixa de
-- ser lista JSON e passa a ser um serviço só.
-- ===========================================================================

-- ------------------------------------------------------- 1. a pasta
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS numero       TEXT;
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS status       TEXT DEFAULT 'Ativo';
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS aberto_em    TEXT;
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS alta_em      TEXT;
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS alta_motivo  TEXT;
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS observacao   TEXT;
ALTER TABLE prontuario ADD COLUMN IF NOT EXISTS reativado_em TEXT;

-- ------------------------------------------------- 2. os lançamentos
-- `arquivado` e não DELETE: registro clínico não se apaga. Some das telas,
-- continua no banco e volta com um clique.
CREATE TABLE IF NOT EXISTS prontuario_registros (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prontuario_id INTEGER NOT NULL,
  tipo          TEXT NOT NULL,
  texto         TEXT,
  data          TEXT,
  profissional  TEXT,
  anexo         TEXT,
  arquivado     INTEGER DEFAULT 0,
  arquivado_em  TEXT,
  usuario_id    INTEGER,
  criado        TEXT,
  atualizado    TEXT
);
CREATE INDEX IF NOT EXISTS idx_reg_pront ON prontuario_registros(prontuario_id);

-- --------------------------------------------------- 3. a linha do tempo
-- O que sobrevive quando a pessoa sai e volta: quem abriu a pasta, quem deu
-- alta, o que mudou numa evolução. `detalhe` é cifrado pela aplicação porque
-- carrega trechos do texto clínico.
CREATE TABLE IF NOT EXISTS historico (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidade     TEXT NOT NULL,
  entidade_id  INTEGER NOT NULL,
  evento       TEXT NOT NULL,
  detalhe      TEXT,
  usuario_id   INTEGER,
  usuario_nome TEXT,
  criado       TEXT
);
CREATE INDEX IF NOT EXISTS idx_hist_ent ON historico(entidade, entidade_id);

-- ------------------------------- 4. o agendamento aponta para a pasta
-- O sentido do vínculo inverte: era `prontuario.atendimento_id` (a pasta
-- apontando para UM agendamento), passa a ser `atendimentos.prontuario_id` —
-- uma pasta reúne MUITOS agendamentos ao longo do acompanhamento.
ALTER TABLE atendimentos ADD COLUMN IF NOT EXISTS prontuario_id INTEGER;
CREATE INDEX IF NOT EXISTS idx_atend_pront ON atendimentos(prontuario_id);

-- ================== CONVERSÃO DO FORMATO ANTIGO ==========================
-- Tudo o que depende das colunas velhas vive dentro deste bloco, guardado pela
-- existência de `prontuario.avaliacao`. Assim rodar a migração DE NOVO não
-- estoura: a segunda passada encontra a guarda falsa e pula direto para os
-- índices. Sem isso, uma falha no meio deixaria a migração impossível de
-- repetir — que é justamente quando alguém tenta repetir.
DO $conversao$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns
              WHERE table_schema = 'public' AND table_name = 'prontuario'
                AND column_name = 'avaliacao') THEN

    -- vínculo antigo (pasta → agendamento) passa para o lado do agendamento
    UPDATE atendimentos a SET prontuario_id = p.id
      FROM prontuario p
     WHERE a.prontuario_id IS NULL AND p.atendimento_id = a.id;

    -- 5. um serviço por pasta (era lista JSON).
    -- Pega o primeiro da lista: não há como adivinhar a qual dos serviços cada
    -- texto se referia, e inventar essa divisão seria pior do que assumir o
    -- primeiro — que é o que a equipe escolheu primeiro.
    UPDATE prontuario
       SET especialidade = TRIM(BOTH '"' FROM SPLIT_PART(TRIM(BOTH '[]' FROM especialidade), ',', 1))
     WHERE especialidade LIKE '[%';
    UPDATE prontuario SET especialidade = '(sem serviço)'
     WHERE especialidade IS NULL OR TRIM(especialidade) = '';

    -- 6. cada caixa de texto preenchida vira um lançamento datado, com a data
    -- da sessão e o profissional que assinou. Caixa vazia não gera nada.
    INSERT INTO prontuario_registros(prontuario_id, tipo, texto, data, profissional, usuario_id, criado)
    SELECT p.id, t.tipo, t.texto, p.data, p.profissional, p.usuario_id, COALESCE(p.criado, p.data)
      FROM prontuario p
     CROSS JOIN LATERAL (VALUES
            ('avaliacao',      p.avaliacao),
            ('evolucao',       p.evolucao),
            ('plano',          p.plano),
            ('encaminhamento', p.encaminhamentos)
          ) AS t(tipo, texto)
     WHERE t.texto IS NOT NULL AND TRIM(t.texto) <> '';

    -- 7. juntar as linhas repetidas na PRIMEIRA pasta. Uma pessoa com 12
    -- sessões de Psicologia tinha 12 linhas; a regra nova é UMA pasta. A mais
    -- antiga vira a pasta; lançamentos e agendamentos das outras migram para
    -- ela, e as demais linhas somem.
    CREATE TEMP TABLE fusao ON COMMIT DROP AS
    SELECT p.id AS antiga,
           (SELECT MIN(p2.id) FROM prontuario p2
             WHERE p2.paciente_id = p.paciente_id AND p2.especialidade = p.especialidade) AS pasta
      FROM prontuario p;

    UPDATE prontuario_registros r SET prontuario_id = f.pasta
      FROM fusao f WHERE r.prontuario_id = f.antiga AND f.antiga <> f.pasta;

    UPDATE atendimentos a SET prontuario_id = f.pasta
      FROM fusao f WHERE a.prontuario_id = f.antiga AND f.antiga <> f.pasta;

    DELETE FROM prontuario p USING fusao f WHERE p.id = f.antiga AND f.antiga <> f.pasta;

    -- 8. estado inicial da pasta
    UPDATE prontuario
       SET status    = COALESCE(NULLIF(status, ''), 'Ativo'),
           aberto_em = COALESCE(NULLIF(aberto_em, ''), NULLIF(data, ''), criado);

    -- 9. as colunas antigas saem de cena. O conteúdo delas já está em
    -- prontuario_registros; mantê-las seria guardar uma segunda cópia do texto
    -- clínico, desatualizada a partir da primeira edição e presente em todo
    -- backup para sempre.
    ALTER TABLE prontuario DROP COLUMN avaliacao;
    ALTER TABLE prontuario DROP COLUMN evolucao;
    ALTER TABLE prontuario DROP COLUMN plano;
    ALTER TABLE prontuario DROP COLUMN encaminhamentos;
    ALTER TABLE prontuario DROP COLUMN IF EXISTS data;
    ALTER TABLE prontuario DROP COLUMN IF EXISTS atendimento_id;
  END IF;
END
$conversao$;

-- Pasta criada depois da conversão (ou banco novo) também nasce Ativa.
UPDATE prontuario SET status = 'Ativo' WHERE status IS NULL OR TRIM(status) = '';

-- ------------------------------------------------------- 10. as regras
-- UMA pasta por pessoa + serviço. É o índice que sustenta a regra: sem ele,
-- duas telas abertas ao mesmo tempo criariam duas pastas do mesmo par e o
-- acompanhamento nasceria partido em dois.
CREATE UNIQUE INDEX IF NOT EXISTS idx_pront_unico ON prontuario(paciente_id, especialidade);
-- número da pasta não se repete
CREATE UNIQUE INDEX IF NOT EXISTS idx_pront_numero ON prontuario(numero) WHERE numero IS NOT NULL;
